### ISSUE TITLE
Inf + 1 returns NaN

### ISSUE THREAD

**Issue by mtanneau** [dzhang314/MultiFloats.jl#13]
There seems to be something wrong with how `Inf` is treated when higher precision is used:
```julia
julia> Float64x1(-Inf) - 1
-Inf
julia> Float64x2(-Inf) - 1  # Same happens for Float64x3, etc
NaN
```
and
```julia
julia> Float64x1(Inf) + 1
Inf
julia> Float64x2(Inf) + 1  # Same happens for Float64x3, etc
NaN
```

**Comment by dzhang314** [comment]
Hey @mtanneau , the remarks from [the comment I left on your other issue](https://github.com/dzhang314/MultiFloats.jl/issues/12#issuecomment-751151737) also apply here. Adding the link for reference.
