### ISSUE TITLE
exp2, exp10, log2, log10 implimentation

### ISSUE THREAD

**Issue by oscardssmith** [dzhang314/MultiFloats.jl#16]
It is probably a good idea to use `exp2` as the fundamental exponential function (it has fewer roundings) and then just implement `exp` and `exp10` with an extra multiple by `log2(e)` and `log2(10)` respectively. A similar strategy can be used for logarithms.

**Comment by dzhang314** [comment]
Hey @oscardssmith , thanks for your interest in **MultiFloats.jl**! This is a great idea, as it simplifies the argument reduction step from subtracting an integer multiple of `log(2)` to simply subtracting an integer. I'll give this a shot, and if the benchmarks turn out favorably, you can expect to see this implemented in the next release.

**Comment by dzhang314** [comment]
Closing this issue to track in #28 instead.
