### ISSUE TITLE
^ not defined.

### ISSUE THREAD

**Issue by lrnv** [dzhang314/MultiFloats.jl#25]
I have the following stacktrace: 

```julia
ERROR: ^ not defined for MultiFloat{Float64, 4}
Stacktrace:
  [1] error(::String, ::String, ::Type)
    @ Base .\error.jl:42
  [2] no_op_err(name::String, T::Type)
    @ Base .\promotion.jl:395
  [3] ^(x::MultiFloat{Float64, 4}, y::MultiFloat{Float64, 4})
```

**Comment by dzhang314** [comment]
Hey @lrnv, thanks for your interest in **MultiFloats.jl**! I plan to add a `^` operator for `MultiFloat` types once I have a fast implementation of `exp` and `log`, which is being tracked in #28.
