### ISSUE TITLE
Convertion error 

### ISSUE THREAD

**Issue by lrnv** [dzhang314/MultiFloats.jl#26]
I ran into a hole in the mesh of methods. 

Convertion from Complex is ambiguous since there is a function that creates a multifloat from limbs. Defining : 

````
MultiFloat{T, N}(z::Complex) where {T, N} = MultiFloat{T, N}(BigFloat(z))
````

filled the hole.

**Comment by dzhang314** [comment]
Hey @lrnv, thanks for pointing this out! This has been fixed in [commit c054c9e](https://github.com/dzhang314/MultiFloats.jl/commit/c054c9e5136fd9c3ad11550bd7e317c15e00e515).
