### ISSUE TITLE
Support a^b

### ISSUE THREAD

**Issue by lrnv** [dzhang314/MultiFloats.jl#8]
if A and B are MultiFloats, then `a^b` should return a proper output. For the moment i fall back to `exp(b*log(a))`

**Comment by dzhang314** [comment]
Hey @lrnv , this is exactly the implementation strategy I plan to use for `a^b` as well, once `exp` and `log` are implemented as per your other issue. I might also add special cases for `b` being a small integer or half-integer, if that turns out to be more efficient.
